# Generated by Django 5.2.5 on 2025-09-02 11:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('ics_url', models.URLField()),
                ('timezone', models.CharField(default='Europe/Brussels', max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('last_synced', models.DateTimeField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('hostname', models.CharField(help_text="Pi's hostname used by the device and to identify it when it calls home.", max_length=255, unique=True)),
                ('host', models.CharField(help_text="How the server reaches the device, e.g. 'http://hallway-pi:8080' or 'http://192.168.1.52:8080'", max_length=255)),
                ('timezone', models.CharField(default='Europe/Brussels', max_length=64)),
                ('default_mode', models.CharField(choices=[('news', 'Newspaper'), ('photo', 'Photo')], default='photo', max_length=16)),
                ('override_mode', models.CharField(choices=[('news', 'Newspaper'), ('photo', 'Photo')], default=None, max_length=16, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Display',
                'verbose_name_plural': 'Displays',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('CALENDAR', 'Get calendar'), ('RSS', 'Get RSS'), ('WEATHER', 'Get weather'), ('PUSH', 'Push to displays'), ('ART', 'Generate art'), ('NEWSPAPER', 'Generate newspaper'), ('CLASSIFY', 'Classify image'), ('MANUAL_TRIGGER', 'Manually triggered'), ('DASHBOARD', 'Generate dashboard'), ('DUMMY', 'Dummy job to test the scheduler and the commands')], max_length=64)),
                ('job_type', models.CharField(choices=[('CRON', 'Triggered by chron'), ('MANUAL', 'Triggered manually')], max_length=64)),
                ('cron', models.CharField(help_text="Cron format, e.g. '0 5 * * *'", max_length=64, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('last_run_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('SKIPPED', 'Skipped'), ('ERROR', 'Error'), ('QUEUED', 'Queued')], max_length=64, null=True)),
                ('last_run_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MinuteSystemSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.DateTimeField(db_index=True, unique=True)),
                ('cpu_percent_avg', models.FloatField()),
                ('mem_total', models.BigIntegerField()),
                ('mem_used_avg', models.BigIntegerField()),
                ('mem_available_avg', models.BigIntegerField()),
                ('swap_total', models.BigIntegerField(null=True)),
                ('swap_used_avg', models.BigIntegerField(null=True)),
                ('rx_bps_avg', models.FloatField(null=True)),
                ('tx_bps_avg', models.FloatField(null=True)),
            ],
            options={
                'ordering': ['-minute'],
            },
        ),
        migrations.CreateModel(
            name='PrerenderedDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('classification', models.JSONField(default=None, null=True)),
                ('has_variants', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=None, null=True)),
                ('finished_at', models.DateTimeField(default=None, null=True)),
                ('runtime_ms', models.PositiveIntegerField(default=None, null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('SKIPPED', 'Skipped'), ('ERROR', 'Error'), ('QUEUED', 'Queued')], max_length=20)),
                ('summary', models.CharField(blank=True, default='', max_length=500)),
                ('error', models.TextField(blank=True, default='')),
                ('params', models.JSONField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='dashboard.job')),
            ],
        ),
        migrations.CreateModel(
            name='JobLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARN', 'Warning'), ('ERROR', 'Error')], db_index=True, default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('context', models.JSONField(default=None, null=True)),
                ('seq', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dashboard.execution')),
            ],
        ),
        migrations.CreateModel(
            name='DayForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('generated_at', models.DateTimeField(db_index=True)),
                ('temp_day', models.FloatField()),
                ('temp_min', models.FloatField()),
                ('temp_max', models.FloatField()),
                ('temp_night', models.FloatField()),
                ('temp_eve', models.FloatField()),
                ('temp_morn', models.FloatField()),
                ('feels_day', models.FloatField()),
                ('feels_night', models.FloatField()),
                ('feels_eve', models.FloatField()),
                ('feels_morn', models.FloatField()),
                ('pressure', models.IntegerField()),
                ('humidity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('dew_point', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('wind_deg', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)])),
                ('wind_gust', models.FloatField(blank=True, null=True)),
                ('clouds', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('uvi', models.FloatField()),
                ('precipitation_probability', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('rain', models.FloatField(blank=True, null=True)),
                ('snow', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.location')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(default=None, null=True)),
                ('art_style', models.CharField(choices=[('KEEP_PHOTO', 'Keep the original'), ('COMMUNIST_POSTER', 'Communist Poster'), ('STUDIO_GHIBLI_STYLE', 'Studio Ghibli Style'), ('RETRO_PIXEL_ART', 'Retro Pixel Art'), ('POINTILLISM_HALFTONE', 'Pointillism / Halftone'), ('MARKER_DRAWING', 'Marker Drawing'), ('CUBISM_ABSTRACT_FACE', 'Cubism Abstract Face'), ('WARHOL_POP_ART', 'Warhol Pop Art'), ('WOODCUT_LINOCUT', 'Woodcut / Linocut'), ('MINIMAL_VECTOR_PORTRAIT', 'Minimal Vector Portrait'), ('CHILDRENS_BOOK_ILLUSTRATION', "Children's Book Illustration"), ('PIXAR_STYLE', 'Pixar Style'), ('DISNEY_CLASSIC', 'Disney Classic'), ('SPIDERVERSE_COMIC', 'Spiderverse Comic'), ('GRITTY_WESTERN_COMICS', 'Gritty Western Comics'), ('MOEBIUS_FRENCH_SCI_FI', 'Moebius (French Sci-Fi)'), ('COMIC_BOOK_VIGNETTE', 'Comic Book Vignette'), ('MANGA_DYNAMIC', 'Manga Dynamic'), ('GHIBLI_GROUP_SCENE', 'Ghibli Group Scene'), ('IMPRESSIONIST_BRUSHWORK', 'Impressionist Brushwork'), ('SILHOUETTE_COLOR_BLOCKS', 'Silhouette Color Blocks'), ('STENCIL_BANKSY_STYLE', 'Stencil (Banksy Style)'), ('INK_WATERCOLOR', 'Ink Watercolor'), ('RETRO_ZOO_POSTER', 'Retro Zoo Poster'), ('NATURALIST_SKETCH', 'Naturalist Sketch'), ('CARTOON_MASCOT', 'Cartoon Mascot'), ('PIXEL_SPRITE_ANIMAL', 'Pixel Sprite Animal'), ('LOWPOLY_GEOMETRIC', 'Low-Poly Geometric'), ('PAPERCUT_LAYER_ART', 'Papercut Layer Art'), ('TOTEM_MYTHOLOGICAL', 'Totem / Mythological'), ('UKIYOE_WOODBLOCK', 'Ukiyo-e Woodblock'), ('PENCIL_GRAPHITE', 'Pencil / Graphite'), ('PASTEL_POSTER', 'Pastel Poster'), ('SILKSCREEN_PRINT', 'Silkscreen Print'), ('GEOMETRIC_ABSTRACTION', 'Geometric Abstraction'), ('ART_DECO_TRAVEL_POSTER', 'Art Deco Travel Poster'), ('WATERCOLOR_WASH', 'Watercolor Wash'), ('CHARCOAL_DRAWING', 'Charcoal Drawing'), ('NOIR_COMIC_SCENE', 'Noir Comic Scene'), ('CYBERPUNK_POSTER', 'Cyberpunk Poster'), ('SILKSCREEN_SKYLINE', 'Silkscreen Skyline'), ('ISOMETRIC_PIXEL_CITY', 'Isometric Pixel City'), ('CONSTRUCTIVIST_POSTER', 'Constructivist Poster'), ('WATERCOLOR_CITYSCAPE', 'Watercolor Cityscape'), ('VECTOR_FLAT_ILLUSTRATION', 'Vector Flat Illustration'), ('BLUEPRINT_TECHNICAL', 'Blueprint / Technical'), ('WOODCUT_ENGRAVING', 'Woodcut Engraving'), ('ART_DECO_ARCHITECTURAL_POSTER', 'Art Deco Architectural Poster'), ('POP_MINIMALISM', 'Pop Minimalism'), ('SURREALIST_DECONSTRUCTION', 'Surrealist Deconstruction'), ('STAINED_GLASS_STYLE', 'Stained Glass Style'), ('LINEART_SKETCH', 'Lineart Sketch'), ('BOTANICAL_PLATE', 'Botanical Plate'), ('INK_WASH_PAINTING', 'Ink Wash Painting'), ('STENCIL_LEAVES', 'Stencil Leaves'), ('CUTPAPER_COLLAGE', 'Cut-Paper Collage'), ('ETCHING_COPPERPLATE', 'Etching / Copperplate'), ('OUTLINE_WITH_COLOR', 'Outline with Color'), ('ART_NOUVEAU_FLORAL', 'Art Nouveau Floral'), ('BAUHAUS_POSTER', 'Bauhaus Poster'), ('SUPREMATISM_MINIMAL_SHAPES', 'Suprematism (Minimal Shapes)'), ('OP_ART_HIGH_CONTRAST', 'Op-Art High Contrast'), ('DUOTONE_POSTER', 'Duotone Poster'), ('PATENT_LINE_DRAWING', 'Patent Line Drawing'), ('VINTAGE_PRODUCT_POSTER', 'Vintage Product Poster'), ('ISOMETRIC_PIXEL_OBJECT', 'Isometric Pixel Object')], default=None, max_length=64, null=True)),
                ('source_quality', models.CharField(choices=[('NOT_SUITED', 'Not suited'), ('BAD', 'Bad'), ('PASSABLE', 'Passable'), ('GOOD', 'Good'), ('VERY_GOOD', 'Very good')])),
                ('content_type', models.CharField(choices=[('PERSON', 'Person'), ('PEOPLE', 'People'), ('ANIMAL', 'Animal'), ('LANDSCAPE', 'Landscape'), ('CITY', 'City'), ('BUILDING', 'Building'), ('NATURE', 'Nature'), ('ART', 'Art'), ('OBJECT', 'Object'), ('OTHER', 'Other')])),
                ('photorealist', models.BooleanField()),
                ('favourite', models.BooleanField()),
                ('score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendered_assets', to='dashboard.sourceimage')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_id', models.IntegerField(blank=True, null=True)),
                ('main_type', models.CharField(max_length=40)),
                ('description', models.CharField(blank=True, max_length=120)),
                ('day_forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_details', to='dashboard.dayforecast')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Mon'), (1, 'Tue'), (2, 'Wed'), (3, 'Thu'), (4, 'Fri'), (5, 'Sat'), (6, 'Sun')])),
                ('start_time', models.TimeField(help_text='Inclusive local start')),
                ('end_time', models.TimeField(help_text="Exclusive local end; use 00:00 for 'until midnight'")),
                ('mode', models.CharField(choices=[('news', 'Newspaper'), ('photo', 'Photo')], default='photo', max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_rules', to='dashboard.display')),
            ],
            options={
                'verbose_name': 'Weekly Rule',
                'verbose_name_plural': 'Weekly Rules',
                'ordering': ['display', 'weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='CalendarOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('instance_start', models.DateTimeField(db_index=True)),
                ('instance_end', models.DateTimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('location', models.CharField(default=None, max_length=500, null=True)),
                ('description', models.TextField(default='No description')),
                ('canceled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='dashboard.calendarsource')),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'instance_start'], name='dashboard_c_source__fc2728_idx'), models.Index(fields=['instance_start'], name='dashboard_c_instanc_7824d4_idx')],
                'unique_together': {('source', 'uid', 'instance_start')},
            },
        ),
        migrations.AddIndex(
            model_name='dayforecast',
            index=models.Index(fields=['location', 'date'], name='dashboard_d_locatio_828525_idx'),
        ),
        migrations.AddConstraint(
            model_name='dayforecast',
            constraint=models.UniqueConstraint(fields=('location', 'date', 'generated_at'), name='uniq_day_forecast_per_run'),
        ),
        migrations.AddIndex(
            model_name='weeklyrule',
            index=models.Index(fields=['display', 'weekday', 'active'], name='dashboard_w_display_ba924e_idx'),
        ),
    ]
