# Generated by Django 5.2.5 on 2025-08-23 12:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='dashboard_l_latitud_6e7793_idx')],
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(db_index=True)),
                ('generated_at', models.DateField(db_index=True)),
                ('time_label', models.TextField(max_length=100)),
                ('icon_main', models.CharField(choices=[('sunny', 'Sunny'), ('partly_cloudy', 'Partly cloudy'), ('cloudy', 'Cloudy'), ('rain', 'Rain'), ('showers', 'Showers'), ('thunder', 'Thunder'), ('fog', 'Fog'), ('snow', 'Snow'), ('windy', 'Windy')], default='sunny', max_length=20)),
                ('icon_transition', models.CharField(choices=[('sunny', 'Sunny'), ('partly_cloudy', 'Partly cloudy'), ('cloudy', 'Cloudy'), ('rain', 'Rain'), ('showers', 'Showers'), ('thunder', 'Thunder'), ('fog', 'Fog'), ('snow', 'Snow'), ('windy', 'Windy')], max_length=20, null=True)),
                ('temperature_c', models.DecimalField(decimal_places=1, max_digits=4)),
                ('precip_prob', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('wind_bft', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)])),
                ('wind_dir', models.CharField(choices=[('N', 'N'), ('NO', 'No'), ('O', 'O'), ('ZO', 'Zo'), ('Z', 'Z'), ('ZW', 'Zw'), ('W', 'W'), ('NW', 'Nw')], default='N', max_length=2)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.location')),
            ],
            options={
                'ordering': ['at'],
                'unique_together': {('location', 'at')},
            },
        ),
        migrations.CreateModel(
            name='WeatherSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_time', models.DateTimeField(db_index=True)),
                ('temperature_c', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precip_mm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('wind_ms', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wind_gust_ms', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cloud_cover_pct', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('rh_pct', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mslp_hpa', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.location')),
            ],
            options={
                'ordering': ['location', 'valid_time'],
                'indexes': [models.Index(fields=['location', 'valid_time'], name='dashboard_w_locatio_3901d4_idx')],
                'unique_together': {('location', 'valid_time')},
            },
        ),
    ]
