# Generated by Django 5.2.5 on 2025-08-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='icon',
            field=models.CharField(choices=[('sunny', 'Sunny'), ('partly_cloudy', 'Partly cloudy'), ('cloudy', 'Cloudy'), ('rain', 'Rain'), ('showers', 'Showers'), ('thunder', 'Thunder'), ('fog', 'Fog'), ('snow', 'Snow'), ('windy', 'Windy')], default='sunny', max_length=20),
        ),
    ]
